
const G='#8a7e6b', BD='#e7e1d4', RL='#f0ebe0', FR='#2D4A3E', DK='#20362D';
const pill=(t,k)=>{const m={g:['#eef6f0','#2f6b45','#cfe3d5'],a:['#fff7df','#8a640f','#e7ce80'],n:['#eef1f2','#626d74','#dde3e4'],b:['#e9eef8','#4a5691','#cfd8ef'],r:['#fbeeec','#9c3b34','#eccfc9']}[k||'n'];
return `<span style="display: inline-block; white-space: nowrap; padding: 2px 8px; background: ${m[0]}; color: ${m[1]}; border: 1px solid ${m[2]}; font-size: 12px">${t}</span>`;};
const eyebrow=t=>`<div style="font-size: 10px; letter-spacing: .16em; text-transform: uppercase; color: ${G}; font-weight: 700">${t}</div>`;
const secHead=(t,note,act)=>`<div style="display: flex; align-items: baseline; gap: 12px; padding: 13px 20px; border-bottom: 1px solid ${BD}; background: #fff">${eyebrow(t)}${note?`<div style="font-size: 12px; color: #6b645d">${note}</div>`:''}${act?`<div style="margin-left: auto; font-size: 12px; color: #946f33">${act}</div>`:''}</div>`;
const TABS=['Overview','Planning','People','Money','Vendors','The Day','Covenant','Documents'];
const SUB={Overview:['Dashboard','Essentials','Notes'],Planning:['Timeline &amp; Tasks','Smart Calendar','Appointments','Weekend Logistics'],People:['Guest List','Households','Contacts','Wedding Party','Table Layout','Gifts'],Money:['Budget','Payments','Contracts &amp; Invoices'],Vendors:['Venue &amp; Vendors','Catering &amp; Menu','Entertainment','Shot Lists'],'The Day':['Wedding Day Timeline','Ceremony &amp; Reception','Weekend Logistics'],Covenant:['Vision &amp; Foundation','Prayer Journal','Premarital Counseling','Marriage Rhythms'],Documents:['Vision Board','Share Packets','Email Templates','Print Centre','Database Hub']};
const topbar=`<div style="flex: 0 0 auto; height: 52px; background: ${FR}; display: flex; align-items: center; gap: 16px; padding: 0 20px">
  <div style="display: flex; align-items: center; gap: 10px; padding-right: 18px; border-right: 1px solid rgba(212,184,150,.25)"><span style="color: #D4B896; font-size: 15px">&#10022;</span><span style="font-family: 'Cormorant Garamond', Georgia, serif; font-size: 19px; letter-spacing: .04em; color: #F4EFE6">The Covenant Wedding Planner</span></div>
  <div style="display: flex; align-items: center; gap: 8px; font-size: 13px; color: rgba(244,239,230,.85)"><span style="width: 20px; height: 20px; border-radius: 3px; background: rgba(212,184,150,.22); color: #D4B896; font-size: 10px; font-weight: 700; display: inline-flex; align-items: center; justify-content: center">AK</span>Ama &amp; Kwesi · 8 November 2026<svg viewBox="0 0 24 24" style="width: 13px; height: 13px; fill: none; stroke: rgba(244,239,230,.6); stroke-width: 2.2; stroke-linecap: round"><path d="m6 9 6 6 6-6"></path></svg></div>
  <div style="flex: 1 1 auto; max-width: 400px; margin: 0 auto; display: flex; align-items: center; gap: 8px; height: 32px; padding: 0 11px; border: 1px solid rgba(212,184,150,.3); background: rgba(255,255,255,.06)"><svg viewBox="0 0 24 24" style="width: 15px; height: 15px; fill: none; stroke: rgba(244,239,230,.65); stroke-width: 1.7; stroke-linecap: round"><circle cx="11" cy="11" r="7"></circle><path d="m16 16 4 4"></path></svg><span style="font-size: 13px; color: rgba(244,239,230,.6)">Search the planner</span><span style="margin-left: auto; font-family: ui-monospace, monospace; font-size: 11px; color: rgba(244,239,230,.5); border: 1px solid rgba(212,184,150,.3); padding: 1px 5px">⌘K</span></div>
  <div style="margin-left: auto; display: flex; align-items: center; gap: 14px"><span style="display: inline-flex; align-items: center; gap: 6px; font-size: 12px; color: rgba(244,239,230,.7)"><span style="width: 6px; height: 6px; border-radius: 50%; background: #8dc0a0"></span>Saved</span><svg viewBox="0 0 24 24" style="width: 17px; height: 17px; fill: none; stroke: rgba(244,239,230,.8); stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span style="width: 26px; height: 26px; border-radius: 50%; border: 1px solid rgba(212,184,150,.5); color: #D4B896; font-size: 11px; font-weight: 600; display: inline-flex; align-items: center; justify-content: center">MO</span></div>
</div>`;
const tabbar=at=>`<div style="flex: 0 0 auto; height: 46px; background: #fdfcfa; border-bottom: 1px solid ${BD}; display: flex; align-items: stretch; padding: 0 20px">${TABS.map(t=>{const a=t===at;return `<div style="display: flex; align-items: center; ${t==='Covenant'?'gap: 7px; ':''}padding: 0 16px; font-size: 12px; font-weight: 600; letter-spacing: .1em; text-transform: uppercase; color: ${a?DK:'#6b645d'}${a?`; border-bottom: 2px solid ${FR}`:''}">${t==='Covenant'?'<span style="width: 5px; height: 5px; border-radius: 50%; background: #B89968"></span>':''}${t}</div>`}).join('')}</div>`;
const subbar=(tab,active)=>`<div style="flex: 0 0 auto; height: 40px; background: #f9f7f4; border-bottom: 1px solid ${BD}; display: flex; align-items: center; padding: 0 20px; gap: 6px">${SUB[tab].map(s=>s===active?`<div style="display: flex; align-items: center; padding: 5px 11px; background: #ece7dd; font-weight: 600; color: ${DK}; font-size: 13px">${s}</div>`:`<div style="display: flex; align-items: center; padding: 5px 11px; color: #6b645d; font-size: 13px">${s}</div>`).join('')}</div>`;
const railGroup=(title,items,plus)=>`<div><div style="display: flex; align-items: center; justify-content: space-between; font-size: 10px; letter-spacing: .16em; text-transform: uppercase; color: ${G}; font-weight: 700; padding-bottom: 8px; border-bottom: 1px solid ${BD}; margin-bottom: 8px">${title}${plus?'<span style="font-size: 14px; color: #b0a794">+</span>':''}</div><div style="display: flex; flex-direction: column; gap: 1px; font-size: 13px; color: #3f3b34">${items.map(([l,c,a,col])=>`<div style="display: flex; justify-content: space-between; padding: 7px 10px; ${a?`background: #fff; border-left: 2px solid ${FR}; font-weight: 600; color: ${DK}`:'border-left: 2px solid transparent'}">${l}<span style="color: ${col||G}; font-weight: 400">${c}</span></div>`).join('')}</div></div>`;
const railMeter=(title,rows)=>`<div><div style="font-size: 10px; letter-spacing: .16em; text-transform: uppercase; color: ${G}; font-weight: 700; padding-bottom: 8px; border-bottom: 1px solid ${BD}; margin-bottom: 8px">${title}</div><div style="display: flex; flex-direction: column; gap: 9px; font-size: 12px; color: #3f3b34">${rows.map(r=>r.length===3?`<div style="display: flex; flex-direction: column; gap: 4px"><div style="display: flex; justify-content: space-between"><span>${r[0]}</span><span style="color: ${G}">${r[1]}</span></div><div style="height: 4px; background: ${BD}; overflow: hidden"><div style="width: ${r[2]}; height: 100%; background: ${FR}"></div></div></div>`:`<div style="display: flex; justify-content: space-between"><span>${r[0]}</span><span style="color: ${G}">${r[1]}</span></div>`).join('')}</div></div>`;
const rail=(inner,note)=>`<div style="flex: 0 0 224px; border-right: 1px solid ${BD}; background: #f9f5ef; padding: 18px 14px; display: flex; flex-direction: column; gap: 22px">${inner}${note?`<div style="margin-top: auto; border-top: 1px solid ${BD}; padding-top: 14px; font-size: 12px; line-height: 1.6; color: #6b645d">${note}</div>`:''}</div>`;
const btnT=t=>`<div style="display: inline-flex; align-items: center; height: 32px; padding: 0 12px; font-size: 13px; color: #6b645d">${t}</div>`;
const btnS=(t,ic)=>`<div style="display: inline-flex; align-items: center; gap: 7px; height: 32px; padding: 0 14px; border: 1px solid #d9cfba; font-size: 13px; font-weight: 500; color: #3f3b34">${ic||''}${t}</div>`;
const icPrint='<svg viewBox="0 0 24 24" style="width: 14px; height: 14px; fill: none; stroke: currentColor; stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round"><path d="M6 9V4h12v5"></path><rect x="4" y="9" width="16" height="7" rx="1"></rect><path d="M7 16h10v4H7z"></path></svg>';
const icFull='<svg viewBox="0 0 24 24" style="width: 14px; height: 14px; fill: none; stroke: currentColor; stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round"><path d="M15 4h5v5"></path><path d="M9 20H4v-5"></path><path d="M20 4l-7 7"></path><path d="M4 20l7-7"></path></svg>';
const btnP=t=>`<div style="display: inline-flex; align-items: center; height: 32px; padding: 0 16px; background: ${FR}; color: #F4EFE6; font-size: 13px; font-weight: 600">${t}</div>`;
const pageHead=(eb,title,tertiary,exp,primary)=>`<div style="flex: 0 0 auto; padding: 20px 24px 16px; border-bottom: 1px solid ${BD}; display: flex; align-items: flex-end; gap: 24px"><div>${eyebrow(eb)}<h2 style="margin: 6px 0 0; font-size: 20px; font-weight: 600; letter-spacing: -.01em; color: ${DK}; line-height: 1.2">${title}</h2></div><div style="margin-left: auto; display: flex; align-items: center; gap: 8px">${tertiary?btnT(tertiary):''}${btnS('Print section',icPrint)}${btnS('Full editor',icFull)}${btnS(exp||'Export')}${btnP(primary)}</div></div>`;
const stats=list=>`<div style="flex: 0 0 auto; display: flex; border-bottom: 1px solid ${BD}">${list.map(([l,v,c],i)=>`<div style="flex: 1; padding: 14px 24px${i<list.length-1?`; border-right: 1px solid ${RL}`:''}">${eyebrow(l).replace('.16em','.14em')}<div style="font-size: 24px; font-weight: 600; letter-spacing: -.015em; color: ${c||DK}; margin-top: 5px; line-height: 1; font-variant-numeric: tabular-nums">${v}</div></div>`).join('')}</div>`;
const chevron='<svg viewBox="0 0 24 24" style="width: 12px; height: 12px; fill: none; stroke: #a89c85; stroke-width: 2.2; stroke-linecap: round"><path d="m6 9 6 6 6-6"></path></svg>';
const toolbar=(chips,views,sort)=>`<div style="flex: 0 0 auto; padding: 10px 24px; border-bottom: 1px solid ${BD}; background: #fdfcfa; display: flex; align-items: center; gap: 8px">${chips.map(c=>`<div style="display: inline-flex; align-items: center; gap: 6px; height: 28px; padding: 0 11px; border: 1px solid #d9cfba; font-size: 12px; color: #3f3b34">${c}${chevron}</div>`).join('')}${sort?`<div style="display: inline-flex; align-items: center; gap: 6px; height: 28px; padding: 0 10px; font-size: 12px; color: #6b645d"><svg viewBox="0 0 24 24" style="width: 13px; height: 13px; fill: none; stroke: currentColor; stroke-width: 1.8; stroke-linecap: round"><path d="M4 6h16M7 12h10M10 18h4"></path></svg>${sort}</div>`:''}<div style="margin-left: auto; display: flex; border: 1px solid #d9cfba">${views.map((v,i)=>i===0?`<span style="padding: 5px 12px; background: ${FR}; color: #F4EFE6; font-size: 12px; font-weight: 600">${v}</span>`:`<span style="padding: 5px 12px; font-size: 12px; color: #6b645d; border-left: 1px solid #d9cfba">${v}</span>`).join('')}</div></div>`;
const bulkbar=(n,acts)=>`<div style="flex: 0 0 auto; padding: 9px 24px; border-bottom: 1px solid ${BD}; background: #f4f1ea; display: flex; align-items: center; gap: 14px; font-size: 12px; color: #3f3b34"><span style="font-weight: 600; color: ${DK}">${n} selected</span><span style="color: #b0a794">|</span>${acts.map(a=>`<span style="color: #946f33">${a}</span>`).join('')}<span style="margin-left: auto; color: #6b645d">Clear selection</span></div>`;
const th=(t,w,al)=>`<th style="text-align: ${al||'left'}; background: ${DK}; color: #F4EFE6; font-size: 10px; letter-spacing: .12em; text-transform: uppercase; font-weight: 700; padding: 10px 12px; border-bottom: 1px solid #B89968;${w?` width: ${w}px;`:''}">${t}</th>`;
const grp=(t,n)=>`<tr style="background: #f9f5ef"><td colspan="${n}" style="padding: 7px 12px; border-bottom: 1px solid ${BD}; font-size: 10px; font-weight: 700; letter-spacing: .14em; text-transform: uppercase; color: ${G}">${t}</td></tr>`;
const td=(c,al,col)=>`<td style="padding: 9px 12px; border-bottom: 1px solid ${RL};${al?` text-align: ${al}; font-variant-numeric: tabular-nums;`:''}${col?` color: ${col};`:''}">${c}</td>`;
const tr=(cells,state)=>`<tr${state==='sel'?' style="background: #f4f7fb"':state==='foc'?' style="background: #fdfaf4"':''}>${cells.join('')}</tr>`;
const addrow=(n,t)=>`<tr><td style="padding: 9px 12px; text-align: center; color: #cfc6b4">+</td><td colspan="${n-1}" style="padding: 9px 12px; color: #b09f80">${t}</td></tr>`;
const cbox=s=>`<td style="padding: 9px 12px; border-bottom: 1px solid ${RL}; text-align: center; color: ${s?FR:'#cfc6b4'}">${s?'☑':'☐'}</td>`;
const table=(cols,rows)=>`<table style="width: 100%; border-collapse: collapse; font-size: 13px; color: #23211c"><thead><tr>${cols.map(c=>th(c[0],c[1],c[2])).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
const fld=(l,v,col)=>`<div style="display: flex; align-items: center; gap: 12px"><span style="width: 96px; flex: 0 0 auto; color: ${G}">${l}</span><span style="flex: 1; min-width: 0; padding: 6px 9px; border: 1px solid #e0dbd1; color: ${col||'#23211c'}">${v}</span></div>`;
const dSec=t=>`<div style="font-size: 10px; letter-spacing: .16em; text-transform: uppercase; color: ${G}; font-weight: 700; padding-bottom: 7px; border-bottom: 1px solid ${BD}; margin-bottom: 2px">${t}</div>`;
const dRows=rows=>`<div style="display: flex; flex-direction: column; gap: 7px; color: #6b645d">${rows.map(([a,b,c])=>`<div style="display: flex; justify-content: space-between"><span>${a}</span><span style="color: ${c||'#6b645d'}">${b}</span></div>`).join('')}</div>`;
const dNote=t=>`<div style="padding: 8px 9px; border: 1px solid #e0dbd1; color: #6b645d; line-height: 1.55; font-size: 13px">${t}</div>`;
const drawer=(eb,title,pills,tabs,body,f1,f2)=>`<div style="flex: 0 0 360px; border-left: 1px solid ${BD}; background: #fff; display: flex; flex-direction: column">
  <div style="padding: 16px 18px; border-bottom: 1px solid ${BD}; background: #f9f5ef">
    <div style="display: flex; align-items: center; gap: 8px; font-size: 10px; letter-spacing: .16em; text-transform: uppercase; color: ${G}; font-weight: 700"><span>${eb}</span><span style="margin-left: auto; color: #b0a794; font-size: 15px; letter-spacing: 0">✕</span></div>
    <div style="font-size: 16px; font-weight: 600; letter-spacing: -.01em; color: ${DK}; margin-top: 8px; line-height: 1.35">${title}</div>
    <div style="display: flex; gap: 6px; margin-top: 10px">${pills}</div>
    <div style="display: flex; margin-top: 12px; border: 1px solid #d9cfba">${tabs.map((t,i)=>i===0?`<span style="flex: 1; text-align: center; padding: 5px 0; background: ${FR}; color: #F4EFE6; font-weight: 600; font-size: 12px;">${t}</span>`:`<span style="flex: 1; text-align: center; padding: 5px 0; color: #6b645d; font-size: 12px; border-left: 1px solid #d9cfba">${t}</span>`).join('')}</div>
  </div>
  <div style="flex: 1 1 auto; min-height: 0; overflow: auto; padding: 16px 18px; display: flex; flex-direction: column; gap: 12px; font-size: 13px">${body}</div>
  <div style="margin-top: auto; padding: 12px 18px; border-top: 1px solid ${BD}; display: flex; gap: 8px"><div style="flex: 1; text-align: center; height: 32px; line-height: 32px; background: ${FR}; color: #F4EFE6; font-size: 13px; font-weight: 600">${f1}</div><div style="flex: 1; text-align: center; height: 32px; line-height: 32px; border: 1px solid #d9cfba; font-size: 13px; font-weight: 500; color: #3f3b34">${f2}</div></div>
</div>`;
const screen=(id,name,blurb,o)=>`
    <div id="${id}" style="display: flex; flex-direction: column; gap: 18px; width: 1440px">
      <div style="display: flex; align-items: flex-start; gap: 16px">
        <span style="flex: 0 0 auto; display: inline-flex; align-items: center; justify-content: center; min-width: 34px; height: 26px; padding: 0 9px; border: 1px solid #6b6a5c; border-radius: 4px; font-size: 12px; font-weight: 700; letter-spacing: .06em; color: #e6e1d6; background: #2d3129">${id}</span>
        <div style="display: flex; flex-direction: column; gap: 5px">
          <div style="font-size: 17px; font-weight: 600; color: #f4efe6">${name}</div>
          <div style="font-size: 13px; line-height: 1.6; color: #8f8b83; max-width: 820px">${blurb}</div>
        </div>
      </div>
      <div data-screen-label="${name}" style="width: 1440px; border: 1px solid #33332c; background: #fbfaf8; display: flex; flex-direction: column">
        ${topbar}${tabbar(o.tab)}${subbar(o.tab,o.sub)}
        <div style="flex: 1 1 auto; display: flex; align-items: stretch">
          ${rail(o.rail,o.note)}
          <div style="flex: 1 1 auto; min-width: 0; display: flex; flex-direction: column; background: #fff">
            ${pageHead(o.eb||o.tab,o.title,o.tertiary,o.exp,o.primary)}
            ${o.stats?stats(o.stats):''}
            ${o.tool||''}
            ${o.bulk||''}
            <div style="display: flex; align-items: stretch">
              <div style="flex: 1 1 auto; min-width: 0">${o.body}</div>
              ${o.drawer}
            </div>
          </div>
        </div>
      </div>
    </div>`;
